name: Build Tor Static Binaries

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      tor_version:
        description: 'Tor version (empty for latest)'
        required: false
        default: ''

env:
  OPENSSL_VERSION: "3.2.1"
  LIBEVENT_VERSION: "2.1.12-stable"
  ZLIB_VERSION: "1.3.1"
  ZSTD_VERSION: "1.5.5"
  XZ_VERSION: "5.4.5"

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Get Tor Version
        id: version
        run: |
          if [ -n "${{ inputs.tor_version }}" ]; then
            VERSION="${{ inputs.tor_version }}"
          else
            VERSION=$(curl -s https://dist.torproject.org/ | grep -oP 'tor-\K[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -1)
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT
          echo "Tor version: ${VERSION}"

  build:
    needs: get-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: linux, arch: amd64, target_os: linux, ext: "" }
          - { os: linux, arch: arm64, target_os: linux, ext: "" }
          - { os: windows, arch: amd64, target_os: mingw, ext: ".exe" }
          - { os: windows, arch: arm64, target_os: mingw, ext: ".exe" }
          - { os: darwin, arch: amd64, target_os: darwin, ext: "" }
          - { os: darwin, arch: arm64, target_os: darwin, ext: "" }
          - { os: freebsd, arch: amd64, target_os: freebsd, ext: "" }
          - { os: freebsd, arch: arm64, target_os: freebsd, ext: "" }
    steps:
      - name: Setup and Build
        env:
          TOR_VERSION: ${{ needs.get-version.outputs.version }}
          SERVER_URL: ${{ gitea.server_url || github.server_url }}
          REPOSITORY: ${{ gitea.repository || github.repository }}
          REPO_OWNER: ${{ gitea.repository_owner || github.repository_owner }}
          COMMIT_SHA: ${{ gitea.sha || github.sha }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config git curl wget autoconf automake libtool xz-utils

          mkdir -p $HOME/cross $HOME/deps
          export CROSS_ROOT="$HOME/cross"
          export DEPS_PREFIX="$HOME/deps"
          export PKG_CONFIG_PATH="$DEPS_PREFIX/lib/pkgconfig"

          # Install cross compiler and set variables
          case "${{ matrix.os }}-${{ matrix.arch }}" in
            linux-amd64)
              wget -q https://musl.cc/x86_64-linux-musl-cross.tgz && tar xzf x86_64-linux-musl-cross.tgz -C $CROSS_ROOT
              export PATH="$CROSS_ROOT/x86_64-linux-musl-cross/bin:$PATH"
              export CC=x86_64-linux-musl-gcc CXX=x86_64-linux-musl-g++
              export AR=x86_64-linux-musl-ar RANLIB=x86_64-linux-musl-ranlib STRIP=x86_64-linux-musl-strip
              export CROSS_PREFIX=x86_64-linux-musl- HOST=x86_64-linux-musl
              ;;
            linux-arm64)
              wget -q https://musl.cc/aarch64-linux-musl-cross.tgz && tar xzf aarch64-linux-musl-cross.tgz -C $CROSS_ROOT
              export PATH="$CROSS_ROOT/aarch64-linux-musl-cross/bin:$PATH"
              export CC=aarch64-linux-musl-gcc CXX=aarch64-linux-musl-g++
              export AR=aarch64-linux-musl-ar RANLIB=aarch64-linux-musl-ranlib STRIP=aarch64-linux-musl-strip
              export CROSS_PREFIX=aarch64-linux-musl- HOST=aarch64-linux-musl
              ;;
            windows-amd64)
              sudo apt-get install -y mingw-w64
              export CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
              export AR=x86_64-w64-mingw32-ar RANLIB=x86_64-w64-mingw32-ranlib STRIP=x86_64-w64-mingw32-strip
              export CROSS_PREFIX=x86_64-w64-mingw32- HOST=x86_64-w64-mingw32
              ;;
            windows-arm64)
              wget -q https://github.com/mstorsjo/llvm-mingw/releases/download/20241217/llvm-mingw-20241217-ucrt-ubuntu-20.04-x86_64.tar.xz
              tar xJf llvm-mingw-*.tar.xz -C $CROSS_ROOT
              export PATH="$CROSS_ROOT/llvm-mingw-20241217-ucrt-ubuntu-20.04-x86_64/bin:$PATH"
              export CC=aarch64-w64-mingw32-gcc CXX=aarch64-w64-mingw32-g++
              export AR=aarch64-w64-mingw32-ar RANLIB=aarch64-w64-mingw32-ranlib STRIP=aarch64-w64-mingw32-strip
              export CROSS_PREFIX=aarch64-w64-mingw32- HOST=aarch64-w64-mingw32
              ;;
            darwin-amd64)
              sudo apt-get install -y clang libxml2-dev llvm-dev uuid-dev libssl-dev
              git clone --depth 1 https://github.com/tpoechtrager/osxcross.git $CROSS_ROOT/osxcross && cd $CROSS_ROOT/osxcross
              wget -q https://github.com/joseluisq/macosx-sdks/releases/download/14.0/MacOSX14.0.sdk.tar.xz -O tarballs/MacOSX14.0.sdk.tar.xz
              UNATTENDED=1 ./build.sh || true && cd -
              export PATH="$CROSS_ROOT/osxcross/target/bin:$PATH"
              export CC=x86_64-apple-darwin23-clang CXX=x86_64-apple-darwin23-clang++
              export AR=x86_64-apple-darwin23-ar RANLIB=x86_64-apple-darwin23-ranlib STRIP=x86_64-apple-darwin23-strip
              export CROSS_PREFIX=x86_64-apple-darwin23- HOST=x86_64-apple-darwin23
              ;;
            darwin-arm64)
              sudo apt-get install -y clang libxml2-dev llvm-dev uuid-dev libssl-dev
              git clone --depth 1 https://github.com/tpoechtrager/osxcross.git $CROSS_ROOT/osxcross && cd $CROSS_ROOT/osxcross
              wget -q https://github.com/joseluisq/macosx-sdks/releases/download/14.0/MacOSX14.0.sdk.tar.xz -O tarballs/MacOSX14.0.sdk.tar.xz
              UNATTENDED=1 ./build.sh || true && cd -
              export PATH="$CROSS_ROOT/osxcross/target/bin:$PATH"
              export CC=aarch64-apple-darwin23-clang CXX=aarch64-apple-darwin23-clang++
              export AR=aarch64-apple-darwin23-ar RANLIB=aarch64-apple-darwin23-ranlib STRIP=aarch64-apple-darwin23-strip
              export CROSS_PREFIX=aarch64-apple-darwin23- HOST=aarch64-apple-darwin23
              ;;
            freebsd-amd64)
              sudo apt-get install -y clang lld
              wget -q https://download.freebsd.org/releases/amd64/14.0-RELEASE/base.txz
              sudo mkdir -p /opt/freebsd && sudo tar xJf base.txz -C /opt/freebsd ./lib ./usr/lib ./usr/include
              export CC=clang CXX=clang++ AR=llvm-ar RANLIB=llvm-ranlib STRIP=llvm-strip
              export CROSS_PREFIX= HOST=x86_64-unknown-freebsd14 FREEBSD_SYSROOT=/opt/freebsd
              export CFLAGS="--sysroot=/opt/freebsd --target=x86_64-unknown-freebsd14"
              export LDFLAGS="--sysroot=/opt/freebsd --target=x86_64-unknown-freebsd14 -fuse-ld=lld"
              ;;
            freebsd-arm64)
              sudo apt-get install -y clang lld
              wget -q https://download.freebsd.org/releases/arm64/aarch64/14.0-RELEASE/base.txz
              sudo mkdir -p /opt/freebsd && sudo tar xJf base.txz -C /opt/freebsd ./lib ./usr/lib ./usr/include
              export CC=clang CXX=clang++ AR=llvm-ar RANLIB=llvm-ranlib STRIP=llvm-strip
              export CROSS_PREFIX= HOST=aarch64-unknown-freebsd14 FREEBSD_SYSROOT=/opt/freebsd
              export CFLAGS="--sysroot=/opt/freebsd --target=aarch64-unknown-freebsd14"
              export LDFLAGS="--sysroot=/opt/freebsd --target=aarch64-unknown-freebsd14 -fuse-ld=lld"
              ;;
          esac

          # Build zlib
          wget -q https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz && tar xzf zlib-${ZLIB_VERSION}.tar.gz && cd zlib-${ZLIB_VERSION}
          if [ "${{ matrix.os }}" = "windows" ]; then
            make -f win32/Makefile.gcc PREFIX=${CROSS_PREFIX} CC=${CC} AR=${AR} RANLIB=${RANLIB}
            mkdir -p $DEPS_PREFIX/include $DEPS_PREFIX/lib && cp zlib.h zconf.h $DEPS_PREFIX/include/ && cp libz.a $DEPS_PREFIX/lib/
          else
            CHOST=${HOST} ./configure --prefix=$DEPS_PREFIX --static && make -j$(nproc) && make install
          fi
          cd ..

          # Build OpenSSL
          wget -q https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && tar xzf openssl-${OPENSSL_VERSION}.tar.gz && cd openssl-${OPENSSL_VERSION}
          case "${{ matrix.os }}-${{ matrix.arch }}" in
            linux-amd64) TARGET="linux-x86_64" ;; linux-arm64) TARGET="linux-aarch64" ;;
            windows-amd64|windows-arm64) TARGET="mingw64" ;;
            darwin-amd64) TARGET="darwin64-x86_64-cc" ;; darwin-arm64) TARGET="darwin64-arm64-cc" ;;
            freebsd-amd64) TARGET="BSD-x86_64" ;; freebsd-arm64) TARGET="BSD-generic64" ;;
          esac
          ./Configure ${TARGET} --prefix=$DEPS_PREFIX --cross-compile-prefix=${CROSS_PREFIX} no-shared no-tests no-ui-console
          make -j$(nproc) && make install_sw && cd ..

          # Build libevent
          wget -q https://github.com/libevent/libevent/releases/download/release-${LIBEVENT_VERSION}/libevent-${LIBEVENT_VERSION}.tar.gz
          tar xzf libevent-${LIBEVENT_VERSION}.tar.gz && cd libevent-${LIBEVENT_VERSION}
          ./configure --prefix=$DEPS_PREFIX --host=${HOST} --enable-static --disable-shared --disable-samples --disable-libevent-regress \
            CFLAGS="-I$DEPS_PREFIX/include $CFLAGS" LDFLAGS="-L$DEPS_PREFIX/lib $LDFLAGS" \
            OPENSSL_CFLAGS="-I$DEPS_PREFIX/include" OPENSSL_LIBS="-L$DEPS_PREFIX/lib -lssl -lcrypto"
          make -j$(nproc) && make install && cd ..

          # Build zstd
          wget -q https://github.com/facebook/zstd/releases/download/v${ZSTD_VERSION}/zstd-${ZSTD_VERSION}.tar.gz && tar xzf zstd-${ZSTD_VERSION}.tar.gz && cd zstd-${ZSTD_VERSION}
          make -j$(nproc) lib-release CC=${CC} AR=${AR} RANLIB=${RANLIB} PREFIX=$DEPS_PREFIX && make install PREFIX=$DEPS_PREFIX
          rm -f $DEPS_PREFIX/lib/libzstd.so* $DEPS_PREFIX/lib/libzstd.dylib* 2>/dev/null || true && cd ..

          # Build xz/liblzma
          wget -q https://github.com/tukaani-project/xz/releases/download/v${XZ_VERSION}/xz-${XZ_VERSION}.tar.gz && tar xzf xz-${XZ_VERSION}.tar.gz && cd xz-${XZ_VERSION}
          ./configure --prefix=$DEPS_PREFIX --host=${HOST} --enable-static --disable-shared --disable-xz --disable-xzdec --disable-lzmadec --disable-lzmainfo --disable-scripts --disable-doc
          make -j$(nproc) && make install && cd ..

          # Download and build Tor
          wget -q "https://dist.torproject.org/tor-${TOR_VERSION}.tar.gz" && tar xzf tor-${TOR_VERSION}.tar.gz && cd tor-${TOR_VERSION}

          CONFIGURE_FLAGS="--prefix=$PWD/../output --host=${HOST} --enable-static-tor --with-libevent-dir=$DEPS_PREFIX --with-openssl-dir=$DEPS_PREFIX --with-zlib-dir=$DEPS_PREFIX --enable-zstd --enable-lzma --disable-asciidoc --disable-manpage --disable-html-manual --disable-module-relay --disable-module-dirauth --disable-systemd --disable-seccomp --disable-libscrypt"

          [ "${{ matrix.os }}" = "windows" ] && CONFIGURE_FLAGS="${CONFIGURE_FLAGS} --enable-static-libevent --enable-static-openssl --enable-static-zlib"
          [ "${{ matrix.os }}" = "darwin" ] && CONFIGURE_FLAGS="${CONFIGURE_FLAGS} --disable-gcc-hardening"

          export CFLAGS="-I$DEPS_PREFIX/include $CFLAGS"
          export LDFLAGS="-L$DEPS_PREFIX/lib $LDFLAGS -static"
          export LIBS="-lzstd -llzma -lssl -lcrypto -levent -lz"
          [ "${{ matrix.os }}" = "windows" ] && export LIBS="$LIBS -lws2_32 -lcrypt32 -lgdi32 -liphlpapi"

          ./configure ${CONFIGURE_FLAGS} || cat config.log
          make -j$(nproc) && make install && cd ..

          # Strip and rename
          ${STRIP} output/bin/tor${{ matrix.ext }} 2>/dev/null || strip output/bin/tor${{ matrix.ext }} 2>/dev/null || true
          mv output/bin/tor${{ matrix.ext }} tor-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

          # Metadata
          cat > tor-${{ matrix.os }}-${{ matrix.arch }}.json << EOF
          {
            "org.opencontainers.image.title": "Tor Static Build",
            "org.opencontainers.image.version": "${TOR_VERSION}",
            "org.opencontainers.image.os": "${{ matrix.os }}",
            "org.opencontainers.image.architecture": "${{ matrix.arch }}",
            "org.opencontainers.image.created": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "org.opencontainers.image.source": "${SERVER_URL}/${REPOSITORY}",
            "org.opencontainers.image.revision": "${COMMIT_SHA}",
            "org.opencontainers.image.vendor": "${REPO_OWNER}",
            "org.opencontainers.image.licenses": "BSD-3-Clause",
            "build.static": "true", "build.stripped": "true",
            "dependencies.openssl": "${OPENSSL_VERSION}",
            "dependencies.libevent": "${LIBEVENT_VERSION}",
            "dependencies.zlib": "${ZLIB_VERSION}",
            "dependencies.zstd": "${ZSTD_VERSION}",
            "dependencies.xz": "${XZ_VERSION}"
          }
          EOF

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tor-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            tor-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
            tor-${{ matrix.os }}-${{ matrix.arch }}.json
          retention-days: 1

  release:
    needs: [get-version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER_URL: ${{ gitea.server_url || github.server_url }}
          REPOSITORY: ${{ gitea.repository || github.repository }}
          TAG: ${{ needs.get-version.outputs.tag }}
          VERSION: ${{ needs.get-version.outputs.version }}
        run: |
          mkdir -p release
          mv artifacts/* release/ 2>/dev/null || mv artifacts/*/* release/
          cd release
          chmod +x tor-linux-* tor-darwin-* tor-freebsd-* 2>/dev/null || true
          sha256sum tor-* > checksums.txt

          # Combined metadata
          echo "[" > metadata.json
          first=true
          for f in *.json; do
            [ "$f" = "metadata.json" ] && continue
            [ "$first" = true ] && first=false || echo "," >> metadata.json
            cat "$f" >> metadata.json
          done
          echo "]" >> metadata.json

          RELEASE_BODY="Tor ${VERSION} static builds for Linux, Windows, macOS, FreeBSD (amd64/arm64)"

          if [ -n "${GITEA_TOKEN}" ]; then
            # Gitea API
            curl -sf -X DELETE -H "Authorization: token ${GITEA_TOKEN}" \
              "${SERVER_URL}/api/v1/repos/${REPOSITORY}/releases/tags/${TAG}" || true

            RELEASE_ID=$(curl -sf -X POST -H "Authorization: token ${GITEA_TOKEN}" \
              -H "Content-Type: application/json" \
              "${SERVER_URL}/api/v1/repos/${REPOSITORY}/releases" \
              -d "{\"tag_name\":\"${TAG}\",\"name\":\"Tor ${VERSION}\",\"body\":\"${RELEASE_BODY}\"}" \
              | jq -r '.id')

            for file in *; do
              [ -f "$file" ] || continue
              curl -sf -X POST -H "Authorization: token ${GITEA_TOKEN}" \
                -F "attachment=@${file}" \
                "${SERVER_URL}/api/v1/repos/${REPOSITORY}/releases/${RELEASE_ID}/assets?name=${file}"
            done
          else
            # GitHub CLI
            gh release delete "${TAG}" --repo "${REPOSITORY}" --yes --cleanup-tag 2>/dev/null || true
            gh release create "${TAG}" --repo "${REPOSITORY}" --title "Tor ${VERSION}" --notes "${RELEASE_BODY}" *
          fi
